### ISSUE TITLE
unix socket connection

### ISSUE THREAD

**Issue by stefanwerfling** [tmigone/pulseaudio#32]
```
const client: PulseAudio = new PulseAudio('unix:/run/pulse/pulseaudio.socket');

await client.connect();
```
I didn't see that unix:/ is taken into account when parsing the address. How is this supposed to work?

Console result:
`Uncaught RangeError [ERR_SOCKET_BAD_PORT]: Port should be >= 0 and < 65536. Received NaN.`

**Comment by SpacingBat3** [comment]
@tmigone I may work on this – you're free to assign me to this issue.

I just saw a lack of the activity on this module, so I'm unsure whenever I should contribute there or fork it and maintain on my own.

---

>```
>const client: PulseAudio = new PulseAudio('unix:/run/pulse/pulseaudio.socket');
>
>await client.connect();
>```

Depending on PulseAudio configuration, this also likely need an authentication cookie. Of course it won't work, since `unix:` is in fact not taken into the account.

**Comment by tmigone** [comment]
@SpacingBat3 I'm a bit split with other things atm but this package is something i'd like to keep maintaining. 

Related to this issue, I saw @CattenLinger recently forked and implemented a fix here https://github.com/CattenLinger/pulseaudio, not sure if it's working or if they intend on submitting a PR back to this repo.

**Comment by SpacingBat3** [comment]
> @SpacingBat3 I'm a bit split with other things atm but this package is something i'd like to keep maintaining.
> 
> Related to this issue, I saw @CattenLinger recently forked and implemented a fix here https://github.com/CattenLinger/pulseaudio, not sure if it's working or if they intend on submitting a PR back to this repo.

Okay then!

I'll then make a PR, my approach is a bit simpler, trying to be close to your code style as well as commit scheme. I've also re-enabled tests that were previously commented for `unix:` addresses and overall prepared tests for the new `TCPSocket` structure – it now includes `type` as a helper value to simply know the interface structure without actually looking for the specific structure.

Once I'll release PR, feel free to review it.

**Comment by SpacingBat3** [comment]
@tmigone Please review and merge #32. 🙂️

**Comment by stefanwerfling** [comment]
@tmigone, @SpacingBat3, Could I suggest a working group, for example Discord or something else, I have a few ideas in mind. I find the project interesting so far. My research has also revealed that I don't have any Pulsaudio on my Linux
own. You could provide a Docker container for this and then put some computers together over the network. Just an idea. I'm glad there was another answer! :smile:

**Comment by SpacingBat3** [comment]
> I find the project interesting so far. My research has also revealed that I don't have any Pulsaudio on my Linux own.

I believe PipeWire can replace PulseAudio and provides the socket/API compatible with it, therefore this module can be also useful for other sound severs and maybe generic in some way as we can just use PulseAudio unix socket to manage both pulse and PipeWire servers.
